# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assembllm < Formula
  desc ""
  homepage "https://github.com/bradyjoslin"
  version "0.1.7"

  on_macos do
    on_intel do
      url "https://github.com/bradyjoslin/assembllm/releases/download/v0.1.7/assembllm_Darwin_x86_64.tar.gz"
      sha256 "bf6792ce57f79fb0f7ceb84f5ff63b7cd0d1794ae43754ed1ccd53555fcab0fe"

      def install
        bin.install "assembllm"
      end
    end
    on_arm do
      url "https://github.com/bradyjoslin/assembllm/releases/download/v0.1.7/assembllm_Darwin_arm64.tar.gz"
      sha256 "52e2c9aeda8f0defd3751d68312bb6c2169e3be4046a928943363c9db162eba1"

      def install
        bin.install "assembllm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bradyjoslin/assembllm/releases/download/v0.1.7/assembllm_Linux_x86_64.tar.gz"
        sha256 "04283a5c6b8b2ae079a2560c08b1906313926ee90fca515f1e8b891884e74dd4"

        def install
          bin.install "assembllm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bradyjoslin/assembllm/releases/download/v0.1.7/assembllm_Linux_arm64.tar.gz"
        sha256 "992262ca0f4a59d924c00ca475ba847daca5841cf3f925c6dee7f3d7562610ec"

        def install
          bin.install "assembllm"
        end
      end
    end
  end
end
