# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assembllm < Formula
  desc ""
  homepage "https://github.com/bradyjoslin"
  version "0.1.4"

  on_macos do
    on_intel do
      url "https://github.com/bradyjoslin/assembllm/releases/download/v0.1.4/assembllm_Darwin_x86_64.tar.gz"
      sha256 "419abbee74a4ee873cdcb079e1f5183dd54a2f14851667e1df4457b743275084"

      def install
        bin.install "assembllm"
      end
    end
    on_arm do
      url "https://github.com/bradyjoslin/assembllm/releases/download/v0.1.4/assembllm_Darwin_arm64.tar.gz"
      sha256 "9c0f0f71ddd2fd8ee13758da74077b2b6c9ddde5b367e798668188a9345dd8ba"

      def install
        bin.install "assembllm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bradyjoslin/assembllm/releases/download/v0.1.4/assembllm_Linux_x86_64.tar.gz"
        sha256 "14d444d1b90d8e9fe78fb5141a2dd5b8d3e5d02d778bcd0e028b3d5c69c26837"

        def install
          bin.install "assembllm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bradyjoslin/assembllm/releases/download/v0.1.4/assembllm_Linux_arm64.tar.gz"
        sha256 "b5eaf27adfef0cf2bb7dff9948230a3f145216476cd06311d4628afcecf01ace"

        def install
          bin.install "assembllm"
        end
      end
    end
  end
end
