# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Assembllm < Formula
  desc ""
  homepage "https://github.com/bradyjoslin"
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/bradyjoslin/assembllm/releases/download/v0.2.0/assembllm_Darwin_x86_64.tar.gz"
      sha256 "0274393134d736ccb207ced9a760ba50782efc91f0e9596b76b8e2a24dc367d2"

      def install
        bin.install "assembllm"
      end
    end
    on_arm do
      url "https://github.com/bradyjoslin/assembllm/releases/download/v0.2.0/assembllm_Darwin_arm64.tar.gz"
      sha256 "cb8cd6b9978d357d7a360576803169d38ff10fd72c8f56ff8946796a9bded764"

      def install
        bin.install "assembllm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bradyjoslin/assembllm/releases/download/v0.2.0/assembllm_Linux_x86_64.tar.gz"
        sha256 "6d38bf0c9e0e16ef2245e7cc454db89652f843273c37ea122514ee6a268746da"

        def install
          bin.install "assembllm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bradyjoslin/assembllm/releases/download/v0.2.0/assembllm_Linux_arm64.tar.gz"
        sha256 "315d8e1154e3950876cc9f2e5948f1786bfdb054fff9a0fb52bae28d864d2ae2"

        def install
          bin.install "assembllm"
        end
      end
    end
  end
end
